[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

[etherscan]
mainnet = { key = "${ETH_API_KEY}", chain = 1, url = "https://api.etherscan.io/api" }
bsc = { key = "${BSC_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
base = { key = "${BASE_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
arbitrum = { key = "${ARB_API_KEY}", chain = 42161, url = "https://api.arbiscan.io/api" }
optimism = { key = "${OP_API_KEY}", chain = 10, url = "https://api-optimistic.etherscan.io/api" }
polygon = { key = "${POL_API_KEY}", chain = 137, url = "https://api.polygonscan.com/api" }
avalanche = { key= "null", chain = 43114, url = "https://api.avascan.info/v2/network/mainnet/evm/43114/etherscan" }
zora = { key = "null", chain = 7777777, url = "https://explorer.zora.energy/api" }
worldChain = { key = "${WC_API_KEY}", chain = 480, url = "https://api.worldscan.org/api" }
zksync = { key = "${ZKSYNC_API_KEY}", chain = 324, url = "https://api-era.zksync.network/api" }
berachain = { key = "${BERACHAIN_API_KEY}", chain = 80094, url = "https://api.berascan.com/api" }
dogeOsTestnet = { key = "null", chain = 221122420, url = "https://blockscout-api.dogeos.doge.xyz/api" }
sonic = {key = "${SONIC_API_KEY}", chain = 146, url = "https://api.sonicscan.org/api"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
